[project]
name = "aoe4-unit-matchup"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "jinja2>=3.1.6",
    "matplotlib>=3.10.1",
    "pandas>=2.2.3",
    "pyqt6>=6.9.0",
]
